entity:
  name: "categorie"
  table: "categorie"
  label: "Catégorie"
  labelPlural: "Catégories"
  defaultPageSize: 10

fields:
  - name: "id"
    type: "uint"
    label: "ID"
    readonly: true
  - name: "libelle"
    type: "string"
    label: "Libellé"
    maxLength: 255
    required: true
  - name: "sens"
    type: "boolean"
    label: "Sens"
  - name: "CodeRegroupement"
    type: "boolean"
    label: "Code Regroupement"
  - name: "commentaire"
    type: "string"
    label: "Commentaire"
    maxLength: 500
  - name: "desactive"
    type: "boolean"
    label: "Désactivé"

forms:
  - name: "categorieList"
    type: "list"
    entity: "categorie"
    config:
      title: "Liste des catégories" # Surcharge du titre par défaut
      columns:
        - "id"
        - "libelle"
        - "desactive"
      columnAlignments: ["center", "left", "center"]
      columnWidths: ["80px", "auto", "100px", "160px"]
      searchableFields: ["id", "libelle"]
      sortableFields: ["id", "libelle"]

  - name: "categorieFiche"
    type: "fiche"
    entity: "categorie"
    config:
      titles:
        create: "Création d’une catégorie"
        update: "Édition d’une catégorie"
      
      groups:
        - name: "Informations Générales"
          fields:
            - name: "id"
              align: "right"
            - name: "libelle"
              size: 50
            - name: "commentaire"
              rows: 4
              size: 50
        - name: "Paramètres"
          fields:
            - name: "sens"
            - name: "CodeRegroupement"
            - name: "desactive"
